In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5302, 6339, 3143, 1104],
 [5302, 6339, 3143, 2570],
 [5302, 2296, 3143, 3008],
 [5830, 3441, 2379, 3673, 7729],
 [5830, 3441, 2379, 3673, 3715],
 [47, 5302, 8565, 3143, 1095],
 [7710, 5386, 4768, 3673]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5302 6339 3143 1104]
 [   0    0    0    0 5302 6339 3143 2570]
 [   0    0    0    0 5302 2296 3143 3008]
 [   0    0    0 5830 3441 2379 3673 7729]
 [   0    0    0 5830 3441 2379 3673 3715]
 [   0    0    0   47 5302 8565 3143 1095]
 [   0    0    0    0 7710 5386 4768 3673]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 243ms/step


array([[[-2.82434355e-02, -4.11835536e-02, -3.61960642e-02,
          2.79272087e-02, -3.99092585e-03,  2.61961110e-02,
          1.67582892e-02,  2.12746002e-02, -1.01320744e-02,
          2.45873369e-02],
        [-2.82434355e-02, -4.11835536e-02, -3.61960642e-02,
          2.79272087e-02, -3.99092585e-03,  2.61961110e-02,
          1.67582892e-02,  2.12746002e-02, -1.01320744e-02,
          2.45873369e-02],
        [-2.82434355e-02, -4.11835536e-02, -3.61960642e-02,
          2.79272087e-02, -3.99092585e-03,  2.61961110e-02,
          1.67582892e-02,  2.12746002e-02, -1.01320744e-02,
          2.45873369e-02],
        [-2.82434355e-02, -4.11835536e-02, -3.61960642e-02,
          2.79272087e-02, -3.99092585e-03,  2.61961110e-02,
          1.67582892e-02,  2.12746002e-02, -1.01320744e-02,
          2.45873369e-02],
        [-1.13722309e-02,  1.94428302e-02, -7.97659159e-03,
         -1.52735785e-03,  4.25699987e-02,  4.74026240e-02,
          1.66885592e-02, -2.99445745e-02, -1.771637